apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: api
  name: api-service
  selfLink: /api/v1/namespaces/default/services/api-service
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    run: api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
