apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Deployment","apiVersion":"apps/v1beta1","metadata":{"name":"frontend","creationTimestamp":null,"labels":{"run":"frontend"}},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"frontend"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"run":"frontend"}},"spec":{"containers":[{"name":"frontend","image":"gcr.io/mcount/frontend","ports":[{"containerPort":3000}],"resources":{}}]}},"strategy":{}},"status":{}}
  creationTimestamp: null
  generation: 1
  labels:
    run: frontend
  name: frontend
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/frontend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: frontend
    spec:
      containers:
        - image: index.docker.io/sastels/mcount_frontend:latest
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
