apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend-service
  selfLink: /api/v1/namespaces/default/services/frontend-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31760
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    run: frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
